--cursor que rescata el tipo de afiliacion para la vista de formulario_afiliacion
CREATE OR REPLACE PROCEDURE sp_listar_tipo_afiliacion(tipo_afiliacion out SYS_REFCURSOR)
IS
BEGIN
    open tipo_afiliacion for select * from tipo_afiliacion;
END;

ID_SOLICITUD        NOT NULL NUMBER(5)  

--NOMBRE_COMPLETO     NOT NULL VARCHAR2(100 CHAR) 
--MAIL                NOT NULL VARCHAR2(50 CHAR) 
--ID_TIPO_AFILIACION  NOT NULL NUMBER(2) 

--NOMBRE_EMPRESA               VARCHAR2(200 CHAR) 
--TELEFONO_CONTACTO            VARCHAR2(18 CHAR)  
---COMENTARIO                   VARCHAR2(250 CHAR)

--FECHA_SOLICITUD     NOT NULL DATE               
--ID_ESTADO_SOLICITUD NOT NULL NUMBER(2)          
--USER_ID                      NUMBER(11)   SOL_AFI_EST_SOL_AFI_FK

--insertar formulario afiliacon, con procedimiento recibiendo parametros opcionales
CREATE OR REPLACE PROCEDURE SP_CREATE_SOLICITUD_AFILIACION(
    P_NOMBRE_COMPLETO IN SOLICITUD_AFILIACION.NOMBRE_COMPLETO%TYPE,
    P_MAIL IN SOLICITUD_AFILIACION.MAIL%TYPE,
    P_ID_TIPO_AFILIACION IN SOLICITUD_AFILIACION.ID_TIPO_AFILIACION%TYPE,
    P_NOMBRE_EMPRESA IN SOLICITUD_AFILIACION.NOMBRE_EMPRESA%TYPE DEFAULT NULL,
    P_TELEFONO_CONTACTO IN SOLICITUD_AFILIACION.TELEFONO_CONTACTO%TYPE DEFAULT NULL,
    P_COMENTARIO IN SOLICITUD_AFILIACION.COMENTARIO%TYPE DEFAULT NULL
    )

IS
BEGIN
    INSERT INTO SOLICITUD_AFILIACION ("NOMBRE_COMPLETO","NOMBRE_EMPRESA","TELEFONO_CONTACTO","MAIL","COMENTARIO","FECHA_SOLICITUD","ID_ESTADO_SOLICITUD","ID_TIPO_AFILIACION","USER_ID")
    VALUES (P_NOMBRE_COMPLETO, P_NOMBRE_EMPRESA,P_TELEFONO_CONTACTO,P_MAIL,P_COMENTARIO,SYSDATE,1,P_ID_TIPO_AFILIACION,NULL);
    
    COMMIT;
END;


    
