# Generated by Django 3.1.1 on 2020-09-13 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id_calidad', models.BooleanField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'calidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClaseLicencia',
            fields=[
                ('id_clase_licencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'clase_licencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostoProceso',
            fields=[
                ('id_costo_proceso', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_transporte', models.BigIntegerField()),
                ('valor_producto_total', models.BigIntegerField()),
                ('aduana', models.BigIntegerField(blank=True, null=True)),
                ('valor_embarque', models.BigIntegerField(blank=True, null=True)),
                ('valor_total_global', models.BigIntegerField()),
            ],
            options={
                'db_table': 'costo_proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleTransporte',
            fields=[
                ('id_detalle_trasporte', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('email_contacto', models.CharField(max_length=50)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id_estado_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'estado_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoOfertaSubasta',
            fields=[
                ('id_estado_oferta_subasta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'estado_oferta_subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoProcesoVenta',
            fields=[
                ('id_estado_proceso_venta', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estado_proceso_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitudAfilacion',
            fields=[
                ('id_estado_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'estado_solicitud_afilacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id_fruta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'fruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.BooleanField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaSubastaProducto',
            fields=[
                ('id_ferta_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField()),
                ('fecha_oferta', models.DateField()),
            ],
            options={
                'db_table': 'oferta_subasta_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaSubastaTransporte',
            fields=[
                ('id_oferta_subasta_transporte', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.BigIntegerField()),
                ('fecha_oferta', models.DateField()),
            ],
            options={
                'db_table': 'oferta_subasta_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('two_char_id_pais', models.CharField(max_length=2)),
                ('three_char_id_pais', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoVenta',
            fields=[
                ('id_proceso_venta', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'proceso_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_subida', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangoPrecioTransporte',
            fields=[
                ('id_rango_transporte', models.FloatField(primary_key=True, serialize=False)),
                ('valor_inferior', models.IntegerField()),
                ('valor_superior', models.IntegerField()),
                ('precio_rango', models.IntegerField()),
            ],
            options={
                'db_table': 'rango_precio_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id_rechazo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'rechazo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id_saldo', models.IntegerField(primary_key=True, serialize=False)),
                ('valor_saldo', models.BigIntegerField()),
            ],
            options={
                'db_table': 'saldo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=120, null=True)),
                ('is_nacional', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudAfilacion',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('nombre_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=18, null=True)),
                ('mail', models.CharField(max_length=50)),
                ('comentario', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_solicitud', models.DateField()),
            ],
            options={
                'db_table': 'solicitud_afilacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubastaProducto',
            fields=[
                ('id_subasta_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subasta_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubastaTransporte',
            fields=[
                ('id_subasta_transporte', models.IntegerField(primary_key=True, serialize=False)),
                ('is_sobrecargo', models.BooleanField()),
                ('is_refrigerador', models.BooleanField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subasta_transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoAfiliacion',
            fields=[
                ('id_tipo_afiliacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tipo_afiliacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRechazo',
            fields=[
                ('id_tipo_rechazo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_rechazo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id_tipo_vehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipo_vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('patente', models.CharField(max_length=7)),
                ('capacidad_carga', models.IntegerField()),
                ('sobrecarga', models.BooleanField()),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.authuser')),
                ('num_licencia', models.CharField(max_length=15)),
                ('num_documento', models.IntegerField()),
            ],
            options={
                'db_table': 'conductor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.authuser')),
                ('fecha_contratacion', models.DateField()),
                ('fecha_nacimeinto', models.DateField()),
                ('rut', models.FloatField()),
                ('dv', models.FloatField()),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
    ]
